from django.urls import path

from academic_core.views import (
    admin_ai_arrange_materials,
    admin_ai_generate_announcement,
    admin_announcement_detail,
    admin_announcements,
    admin_assignments,
    admin_assignment_detail,
    admin_course_material_detail,
    admin_course_materials,
    admin_course_detail,
    admin_courses,
    admin_poll_detail,
    admin_polls,
    admin_settings,
    admin_student_detail,
    admin_students,
    admin_upload_grades,
    admin_run_sync,
    cast_poll_vote,
    finance_dues,
    finance_notifications,
    finance_settle,
    finance_split,
    change_student_password,
    cr_generate_draft,
    get_or_create_blinkit_pools,
    get_bus_schedule,
    get_or_create_cab_pools,
    get_or_create_sell_posts,
    get_active_polls,
    get_dashboard_extras,
    get_or_create_attendance_waivers,
    get_mess_menu,
    get_or_update_student_profile,
    get_student_attendance,
    get_student_readings,
    get_student_timetable,
    login_admin,
    logout_admin,
    update_or_delete_blinkit_pool,
    update_or_delete_cab_pool,
    update_or_delete_sell_post,
)

urlpatterns = [
    path('sharing/cab-pools/', get_or_create_cab_pools, name='sharing-cab-pools'),
    path('sharing/cab-pools/<int:pool_id>/', update_or_delete_cab_pool, name='sharing-cab-pool-detail'),
    path('sharing/blinkit-pools/', get_or_create_blinkit_pools, name='sharing-blinkit-pools'),
    path(
        'sharing/blinkit-pools/<int:pool_id>/',
        update_or_delete_blinkit_pool,
        name='sharing-blinkit-pool-detail',
    ),
    path('sharing/sell-posts/', get_or_create_sell_posts, name='sharing-sell-posts'),
    path('sharing/sell-posts/<int:post_id>/', update_or_delete_sell_post, name='sharing-sell-post-detail'),
    path('attendance/<str:roll_number>/', get_student_attendance, name='student-attendance'),
    path(
        'attendance/<str:roll_number>/waivers/',
        get_or_create_attendance_waivers,
        name='student-attendance-waivers',
    ),
    path('timetable/<str:roll_number>/', get_student_timetable, name='student-timetable'),
    path('bus-schedule/', get_bus_schedule, name='bus-schedule'),
    path('readings/<str:roll_number>/', get_student_readings, name='student-readings'),
    path('mess-menu/', get_mess_menu, name='mess-menu'),
    path('dashboard-extras/', get_dashboard_extras, name='dashboard-extras'),
    path('polls/', get_active_polls, name='polls-active'),
    path('polls/<int:poll_id>/vote/', cast_poll_vote, name='poll-vote'),
    path('finance/split/', finance_split, name='finance-split'),
    path('finance/dues/', finance_dues, name='finance-dues'),
    path('finance/settle/<int:transaction_id>/', finance_settle, name='finance-settle'),
    path('finance/notifications/', finance_notifications, name='finance-notifications'),
    path('profile/<str:roll_number>/', get_or_update_student_profile, name='student-profile'),
    path(
        'profile/<str:roll_number>/change-password/',
        change_student_password,
        name='student-change-password',
    ),
    path('admin/login/', login_admin, name='admin-login'),
    path('admin/logout/', logout_admin, name='admin-logout'),
    path('admin/run-sync/', admin_run_sync, name='admin-run-sync'),
    path('admin/settings/', admin_settings, name='admin-settings'),
    path('admin/students/', admin_students, name='admin-students'),
    path('admin/students/<str:roll_number>/', admin_student_detail, name='admin-student-detail'),
    path('admin/courses/', admin_courses, name='admin-courses'),
    path('admin/courses/<str:course_code>/', admin_course_detail, name='admin-course-detail'),
    path('admin/grades/', admin_upload_grades, name='admin-grades-upload'),
    path('admin/announcements/', admin_announcements, name='admin-announcements'),
    path('admin/assignments/', admin_assignments, name='admin-assignments'),
    path('admin/assignments/<int:assignment_id>/', admin_assignment_detail, name='admin-assignment-detail'),
    path('admin/polls/', admin_polls, name='admin-polls'),
    path('admin/polls/<int:poll_id>/', admin_poll_detail, name='admin-poll-detail'),
    path('cr/generate-draft/', cr_generate_draft, name='cr-generate-draft'),
    path(
        'admin/announcements/<int:announcement_id>/',
        admin_announcement_detail,
        name='admin-announcement-detail',
    ),
    path('admin/course-materials/', admin_course_materials, name='admin-course-materials'),
    path(
        'admin/course-materials/<int:material_id>/',
        admin_course_material_detail,
        name='admin-course-material-detail',
    ),
    path(
        'admin/ai/generate-announcement/',
        admin_ai_generate_announcement,
        name='admin-ai-generate-announcement',
    ),
    path(
        'admin/ai/arrange-materials/',
        admin_ai_arrange_materials,
        name='admin-ai-arrange-materials',
    ),
]
