# Generated by Django 6.0.2 on 2026-03-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('credits', models.IntegerField()),
                ('drive_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='academic_co_name_28c175_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'category'], name='academic_co_date_c6796d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['section'], name='academic_co_section_4cd307_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=20)),
                ('raw_text', models.CharField(max_length=255)),
                ('is_exam', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_core.course')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'start_time'], name='academic_co_date_38ec0f_idx'), models.Index(fields=['course', 'date'], name='academic_co_course__e8414e_idx'), models.Index(fields=['is_exam', 'date'], name='academic_co_is_exam_0f4520_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_attended', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['last_updated'], name='academic_co_last_up_249acf_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
