# Generated by Django 6.0.2 on 2026-03-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'course'], name='academic_co_student_a7d16a_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
