# Generated by Django 6.0.2 on 2026-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0002_student_password_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='target_section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('All', 'All')], default='All', max_length=3),
        ),
    ]
