# Generated by Django 6.0.2 on 2026-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0003_classsession_target_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
