# Generated by Django 6.0.2 on 2026-03-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0006_announcement_attachment_announcement_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWaiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('supporting_file', models.FileField(upload_to='attendance_waivers/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_waivers', to='academic_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_waivers', to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'submitted_at'], name='academic_co_student_8a40be_idx'), models.Index(fields=['course', 'status'], name='academic_co_course__8aac80_idx')],
            },
        ),
    ]
