# Generated by Django 6.0.2 on 2026-03-15 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0007_attendancewaiverrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlinkitPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_block', models.CharField(max_length=80)),
                ('order_deadline', models.TimeField()),
                ('whatsapp_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit WhatsApp number.', regex='^\\d{10}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blinkit_pools', to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='academic_co_is_acti_c29271_idx')],
            },
        ),
        migrations.CreateModel(
            name='CabPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120)),
                ('departure_date', models.DateField(db_index=True)),
                ('time_window', models.CharField(max_length=60)),
                ('available_seats', models.IntegerField()),
                ('whatsapp_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit WhatsApp number.', regex='^\\d{10}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab_pools', to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'departure_date'], name='academic_co_is_acti_daa093_idx'), models.Index(fields=['-created_at'], name='academic_co_created_706a21_idx')],
            },
        ),
    ]
