# Generated by Django 6.0.2 on 2026-03-15 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0008_blinkitpool_cabpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='blinkitpool',
            name='order_type',
            field=models.CharField(choices=[('blinkit', 'Blinkit'), ('night_mess', 'Night Mess')], default='blinkit', max_length=20),
        ),
        migrations.CreateModel(
            name='SellPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('whatsapp_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit WhatsApp number.', regex='^\\d{10}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_posts', to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='academic_co_is_acti_ba3639_idx')],
            },
        ),
    ]
