# Generated by Django 6.0.2 on 2026-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0009_blinkitpool_order_type_sellpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_term_name', models.CharField(default='Term-IX', max_length=30)),
                ('timetable_sheet_url', models.URLField(blank=True, default='')),
                ('attendance_sheet_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='is_ipmo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='GradeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='grades/%Y/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['term_name', '-uploaded_at'], name='academic_co_term_na_9f0b2b_idx')],
            },
        ),
    ]
