# Generated by Django 6.0.2 on 2026-03-15 21:05

import django.db.models.deletion
from django.db import migrations, models


def seed_batches_and_backfill(apps, schema_editor):
    Batch = apps.get_model('academic_core', 'Batch')
    Student = apps.get_model('academic_core', 'Student')
    ClassSession = apps.get_model('academic_core', 'ClassSession')
    AttendanceRecord = apps.get_model('academic_core', 'AttendanceRecord')
    StudentCourse = apps.get_model('academic_core', 'StudentCourse')
    MessMenu = apps.get_model('academic_core', 'MessMenu')
    Announcement = apps.get_model('academic_core', 'Announcement')
    Assignment = apps.get_model('academic_core', 'Assignment')
    GradeDocument = apps.get_model('academic_core', 'GradeDocument')
    TermSettings = apps.get_model('academic_core', 'TermSettings')

    for code in ('IPM01', 'IPM02', 'IPM03'):
        Batch.objects.get_or_create(code=code, defaults={'name': code, 'is_active': True})

    default_batch = Batch.objects.get(code='IPM01')

    Student.objects.filter(batch__isnull=True).update(batch=default_batch)
    ClassSession.objects.filter(batch__isnull=True).update(batch=default_batch)
    AttendanceRecord.objects.filter(batch__isnull=True).update(batch=default_batch)
    StudentCourse.objects.filter(batch__isnull=True).update(batch=default_batch)
    MessMenu.objects.filter(batch__isnull=True).update(batch=default_batch)
    Announcement.objects.filter(batch__isnull=True).update(batch=default_batch)
    Assignment.objects.filter(batch__isnull=True).update(batch=default_batch)
    GradeDocument.objects.filter(batch__isnull=True).update(batch=default_batch)

    settings_rows = list(TermSettings.objects.filter(batch__isnull=True).order_by('id'))
    if settings_rows:
        primary = settings_rows[0]
        primary.batch = default_batch
        primary.save(update_fields=['batch'])
        for duplicate in settings_rows[1:]:
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0010_termsettings_student_is_ipmo_gradedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='academic_co_is_acti_6e2df0_idx')],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='gradedocument',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_documents', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mess_menu_rows', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='academic_core.batch'),
        ),
        migrations.AddField(
            model_name='termsettings',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_settings', to='academic_core.batch'),
        ),
        migrations.RunPython(seed_batches_and_backfill, migrations.RunPython.noop),
    ]
