# Generated by Django 6.0.2 on 2026-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0011_batch_announcement_batch_assignment_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsettings',
            name='birthday_sheet_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='termsettings',
            name='mess_menu_sheet_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
