# Generated by Django 6.0.2 on 2026-03-15 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0012_termsettings_birthday_sheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('ALL', 'All Students in Batch'), ('SECTION_A', 'Section A'), ('SECTION_B', 'Section B'), ('COURSE', 'Specific Course')], db_index=True, default='ALL', max_length=12)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='academic_core.batch')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='academic_core.course')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='academic_core.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='academic_core.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='academic_core.poll')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='academic_core.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['batch', 'target_type'], name='academic_co_batch_i_bc3248_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at', 'created_at'], name='academic_co_expires_e500ee_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'id'], name='academic_co_poll_id_154679_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'option'], name='academic_co_poll_id_7b5e00_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['student', 'poll'], name='academic_co_student_4ddde7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'student')},
        ),
    ]
