# Generated by Django 6.0.2 on 2026-03-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0013_assignment_due_time_poll_polloption_pollvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PeerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('is_settled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_to_receive', to='academic_core.student')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_to_pay', to='academic_core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['debtor', 'is_settled'], name='academic_co_debtor__83cf4b_idx'), models.Index(fields=['creditor', 'is_settled'], name='academic_co_credito_f19d0d_idx')],
            },
        ),
    ]
