# Generated by Django 6.0.2 on 2026-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0014_student_upi_id_peertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertransaction',
            name='creditor_confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='peertransaction',
            name='debtor_confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='peertransaction',
            name='settled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='peertransaction',
            index=models.Index(fields=['is_settled', 'settled_at'], name='academic_co_is_sett_095177_idx'),
        ),
    ]
