# Generated by Django 6.0.2 on 2026-03-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0015_peertransaction_creditor_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic_core.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Students in Batch'), ('SECTION_A', 'Section A'), ('SECTION_B', 'Section B'), ('COURSE', 'Specific Course')], db_index=True, default='ALL', max_length=12),
        ),
        migrations.AddField(
            model_name='assignment',
            name='group_members',
            field=models.TextField(blank=True, default=''),
        ),
    ]
